# -*- coding: utf-8 -*-
"""CPFipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14N1oK0eCwd_DMAL02n7NLuGX8kxfsJG0
"""

def mascara_de_cpf():
  cpf = input('Digite seu cpf ')
  #tratar o cpf
  #tirar espaços no inicio e no final
  cpf = cpf.strip()
  #tirar os . (pontos)
  cpf = cpf.replace('.', '')
  #tirar os traços (-)
  cpf = cpf.replace('-', '')
  if len(cpf) == 11 and cpf.isnumeric():
      cpf = ("{}{}{}.{}{}{}.{}{}{}-{}".format(*cpf))
      print(cpf)
  else:
      print('Digite seu CPF corretamente e digite apenas números')





mascara_de_cpf()